# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fpu_constraints.xdc

# Block Designs: bd/fpu/fpu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu || ORIG_REF_NAME==fpu} -quiet] -quiet

# IP: bd/fpu/ip/fpu_inputStage_0_0/fpu_inputStage_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_inputStage_0_0 || ORIG_REF_NAME==fpu_inputStage_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_preAdder_0_0/fpu_preAdder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_preAdder_0_0 || ORIG_REF_NAME==fpu_preAdder_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_shiftEquExp_0_0/fpu_shiftEquExp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_shiftEquExp_0_0 || ORIG_REF_NAME==fpu_shiftEquExp_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_signAdder_0_0/fpu_signAdder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_signAdder_0_0 || ORIG_REF_NAME==fpu_signAdder_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_addDiffSign_0_0/fpu_addDiffSign_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_addDiffSign_0_0 || ORIG_REF_NAME==fpu_addDiffSign_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_addSameSign_0_0/fpu_addSameSign_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_addSameSign_0_0 || ORIG_REF_NAME==fpu_addSameSign_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_mux_0_0/fpu_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_mux_0_0 || ORIG_REF_NAME==fpu_mux_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_mux_1_0/fpu_mux_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_mux_1_0 || ORIG_REF_NAME==fpu_mux_1_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_mux_2_0/fpu_mux_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_mux_2_0 || ORIG_REF_NAME==fpu_mux_2_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_controlUnit_0_0/fpu_controlUnit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_controlUnit_0_0 || ORIG_REF_NAME==fpu_controlUnit_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_outputStage_0_0/fpu_outputStage_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_outputStage_0_0 || ORIG_REF_NAME==fpu_outputStage_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_multiplier_0_0/fpu_multiplier_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_multiplier_0_0 || ORIG_REF_NAME==fpu_multiplier_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_multLeftShift_0_0/fpu_multLeftShift_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_multLeftShift_0_0 || ORIG_REF_NAME==fpu_multLeftShift_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_multRightShift_0_0/fpu_multRightShift_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_multRightShift_0_0 || ORIG_REF_NAME==fpu_multRightShift_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_xlslice_0_0/fpu_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_xlslice_0_0 || ORIG_REF_NAME==fpu_xlslice_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_mux_3_0/fpu_mux_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_mux_3_0 || ORIG_REF_NAME==fpu_mux_3_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_mux_4_0/fpu_mux_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_mux_4_0 || ORIG_REF_NAME==fpu_mux_4_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_mux_5_0/fpu_mux_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_mux_5_0 || ORIG_REF_NAME==fpu_mux_5_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_flipFlop_0_0/fpu_flipFlop_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_flipFlop_0_0 || ORIG_REF_NAME==fpu_flipFlop_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_xlslice_1_0/fpu_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_xlslice_1_0 || ORIG_REF_NAME==fpu_xlslice_1_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_mux4_1_0_0/fpu_mux4_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_mux4_1_0_0 || ORIG_REF_NAME==fpu_mux4_1_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_multRightShiftUn_0_1/fpu_multRightShiftUn_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_multRightShiftUn_0_1 || ORIG_REF_NAME==fpu_multRightShiftUn_0_1} -quiet] -quiet

# IP: bd/fpu/ip/fpu_flipFlop_1_0/fpu_flipFlop_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_flipFlop_1_0 || ORIG_REF_NAME==fpu_flipFlop_1_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_checkMultExponent_0_0/fpu_checkMultExponent_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_checkMultExponent_0_0 || ORIG_REF_NAME==fpu_checkMultExponent_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_xlslice_2_0/fpu_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_xlslice_2_0 || ORIG_REF_NAME==fpu_xlslice_2_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_xlconstant_0_0/fpu_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_xlconstant_0_0 || ORIG_REF_NAME==fpu_xlconstant_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_mux4_1_1_0/fpu_mux4_1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_mux4_1_1_0 || ORIG_REF_NAME==fpu_mux4_1_1_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_xlconstant_1_0/fpu_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_xlconstant_1_0 || ORIG_REF_NAME==fpu_xlconstant_1_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_xlconstant_2_0/fpu_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_xlconstant_2_0 || ORIG_REF_NAME==fpu_xlconstant_2_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_xlslice_3_0/fpu_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_xlslice_3_0 || ORIG_REF_NAME==fpu_xlslice_3_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_xlslice_3_1/fpu_xlslice_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_xlslice_3_1 || ORIG_REF_NAME==fpu_xlslice_3_1} -quiet] -quiet

# IP: bd/fpu/ip/fpu_xlslice_5_0/fpu_xlslice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_xlslice_5_0 || ORIG_REF_NAME==fpu_xlslice_5_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_orGate_0_0/fpu_orGate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_orGate_0_0 || ORIG_REF_NAME==fpu_orGate_0_0} -quiet] -quiet

# IP: bd/fpu/ip/fpu_xorGate_0_0/fpu_xorGate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpu_xorGate_0_0 || ORIG_REF_NAME==fpu_xorGate_0_0} -quiet] -quiet

# XDC: d:/Rohit BITS Data/3_Third Year/Second Sem/Comp Arch/Vivado/fpu_comparch/fpu_comparch.gen/sources_1/bd/fpu/fpu_ooc.xdc
